/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthControllerCheckV1200Response,
  HealthControllerCheckV1503Response,
} from '../models/index';
import {
    HealthControllerCheckV1200ResponseFromJSON,
    HealthControllerCheckV1200ResponseToJSON,
    HealthControllerCheckV1503ResponseFromJSON,
    HealthControllerCheckV1503ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Health check endpoint
     * Check the health of the service
     */
    async healthControllerCheckV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthControllerCheckV1200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthControllerCheckV1200ResponseFromJSON(jsonValue));
    }

    /**
     * Health check endpoint
     * Check the health of the service
     */
    async healthControllerCheckV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthControllerCheckV1200Response> {
        const response = await this.healthControllerCheckV1Raw(initOverrides);
        return await response.value();
    }

}
