/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaceResult } from './PlaceResult';
import {
    PlaceResultFromJSON,
    PlaceResultFromJSONTyped,
    PlaceResultToJSON,
} from './PlaceResult';

/**
 * 
 * @export
 * @interface AutoCompleteApiResponse
 */
export interface AutoCompleteApiResponse {
    /**
     * 
     * @type {Array<PlaceResult>}
     * @memberof AutoCompleteApiResponse
     */
    data: Array<PlaceResult>;
}

/**
 * Check if a given object implements the AutoCompleteApiResponse interface.
 */
export function instanceOfAutoCompleteApiResponse(value: object): value is AutoCompleteApiResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AutoCompleteApiResponseFromJSON(json: any): AutoCompleteApiResponse {
    return AutoCompleteApiResponseFromJSONTyped(json, false);
}

export function AutoCompleteApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoCompleteApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PlaceResultFromJSON)),
    };
}

export function AutoCompleteApiResponseToJSON(value?: AutoCompleteApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(PlaceResultToJSON)),
    };
}

