/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomerDto
 */
export interface CreateCustomerDto {
    /**
     * XCD Customer user ID
     * @type {string}
     * @memberof CreateCustomerDto
     */
    userId: string;
    /**
     * Customer name
     * @type {string}
     * @memberof CreateCustomerDto
     */
    customerName: string;
    /**
     * Contact email address
     * @type {string}
     * @memberof CreateCustomerDto
     */
    contactEmail: string;
    /**
     * Contact phone number
     * @type {string}
     * @memberof CreateCustomerDto
     */
    contactPhone?: string;
    /**
     * Company ID
     * @type {string}
     * @memberof CreateCustomerDto
     */
    companyId: string;
    /**
     * Company name
     * @type {string}
     * @memberof CreateCustomerDto
     */
    companyName?: string;
    /**
     * Customer location
     * @type {object}
     * @memberof CreateCustomerDto
     */
    location?: object;
    /**
     * Customer status
     * @type {string}
     * @memberof CreateCustomerDto
     */
    status: CreateCustomerDtoStatusEnum;
    /**
     * Total events count
     * @type {number}
     * @memberof CreateCustomerDto
     */
    totalEvents?: number;
}


/**
 * @export
 */
export const CreateCustomerDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;
export type CreateCustomerDtoStatusEnum = typeof CreateCustomerDtoStatusEnum[keyof typeof CreateCustomerDtoStatusEnum];


/**
 * Check if a given object implements the CreateCustomerDto interface.
 */
export function instanceOfCreateCustomerDto(value: object): value is CreateCustomerDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('customerName' in value) || value['customerName'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateCustomerDtoFromJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoFromJSONTyped(json, false);
}

export function CreateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'customerName': json['customerName'],
        'contactEmail': json['contactEmail'],
        'contactPhone': json['contactPhone'] == null ? undefined : json['contactPhone'],
        'companyId': json['companyId'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'],
        'totalEvents': json['totalEvents'] == null ? undefined : json['totalEvents'],
    };
}

export function CreateCustomerDtoToJSON(value?: CreateCustomerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'customerName': value['customerName'],
        'contactEmail': value['contactEmail'],
        'contactPhone': value['contactPhone'],
        'companyId': value['companyId'],
        'companyName': value['companyName'],
        'location': value['location'],
        'status': value['status'],
        'totalEvents': value['totalEvents'],
    };
}

