/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * User email address
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;
    /**
     * User full name
     * @type {string}
     * @memberof CreateUserDto
     */
    fullName: string;
    /**
     * User password hash (for non-SSO users)
     * @type {string}
     * @memberof CreateUserDto
     */
    passwordHash?: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof CreateUserDto
     */
    avatarUrl?: string;
    /**
     * User phone number
     * @type {string}
     * @memberof CreateUserDto
     */
    phone?: string;
    /**
     * User type
     * @type {string}
     * @memberof CreateUserDto
     */
    userType: CreateUserDtoUserTypeEnum;
    /**
     * User status
     * @type {string}
     * @memberof CreateUserDto
     */
    status: CreateUserDtoStatusEnum;
    /**
     * SSO provider (for SSO users)
     * @type {string}
     * @memberof CreateUserDto
     */
    ssoProvider?: string;
    /**
     * SSO user ID (for SSO users)
     * @type {string}
     * @memberof CreateUserDto
     */
    ssoUserId?: string;
}


/**
 * @export
 */
export const CreateUserDtoUserTypeEnum = {
    Admin: 'admin',
    User: 'user',
    Customer: 'customer'
} as const;
export type CreateUserDtoUserTypeEnum = typeof CreateUserDtoUserTypeEnum[keyof typeof CreateUserDtoUserTypeEnum];

/**
 * @export
 */
export const CreateUserDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;
export type CreateUserDtoStatusEnum = typeof CreateUserDtoStatusEnum[keyof typeof CreateUserDtoStatusEnum];


/**
 * Check if a given object implements the CreateUserDto interface.
 */
export function instanceOfCreateUserDto(value: object): value is CreateUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('userType' in value) || value['userType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
    return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'fullName': json['fullName'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'userType': json['userType'],
        'status': json['status'],
        'ssoProvider': json['ssoProvider'] == null ? undefined : json['ssoProvider'],
        'ssoUserId': json['ssoUserId'] == null ? undefined : json['ssoUserId'],
    };
}

export function CreateUserDtoToJSON(value?: CreateUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'fullName': value['fullName'],
        'passwordHash': value['passwordHash'],
        'avatarUrl': value['avatarUrl'],
        'phone': value['phone'],
        'userType': value['userType'],
        'status': value['status'],
        'ssoProvider': value['ssoProvider'],
        'ssoUserId': value['ssoUserId'],
    };
}

