/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomerDto
 */
export interface CreateCustomerDto {
    /**
     * Customer name
     * @type {string}
     * @memberof CreateCustomerDto
     */
    customerName: string;
    /**
     * Contact email address
     * @type {string}
     * @memberof CreateCustomerDto
     */
    contactEmail: string;
    /**
     * Contact phone number
     * @type {string}
     * @memberof CreateCustomerDto
     */
    contactPhone?: string;
    /**
     * Customer location
     * @type {object}
     * @memberof CreateCustomerDto
     */
    location?: object;
    /**
     * Phone country code (e.g., +1, +44, +91)
     * @type {string}
     * @memberof CreateCustomerDto
     */
    countryCode?: string;
}

/**
 * Check if a given object implements the CreateCustomerDto interface.
 */
export function instanceOfCreateCustomerDto(value: object): value is CreateCustomerDto {
    if (!('customerName' in value) || value['customerName'] === undefined) return false;
    if (!('contactEmail' in value) || value['contactEmail'] === undefined) return false;
    return true;
}

export function CreateCustomerDtoFromJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoFromJSONTyped(json, false);
}

export function CreateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'customerName': json['customerName'],
        'contactEmail': json['contactEmail'],
        'contactPhone': json['contactPhone'] == null ? undefined : json['contactPhone'],
        'location': json['location'] == null ? undefined : json['location'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
    };
}

export function CreateCustomerDtoToJSON(value?: CreateCustomerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customerName': value['customerName'],
        'contactEmail': value['contactEmail'],
        'contactPhone': value['contactPhone'],
        'location': value['location'],
        'countryCode': value['countryCode'],
    };
}

