/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEventResponseDto
 */
export interface CreateEventResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof CreateEventResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the CreateEventResponseDto interface.
 */
export function instanceOfCreateEventResponseDto(value: object): value is CreateEventResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateEventResponseDtoFromJSON(json: any): CreateEventResponseDto {
    return CreateEventResponseDtoFromJSONTyped(json, false);
}

export function CreateEventResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEventResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function CreateEventResponseDtoToJSON(value?: CreateEventResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

