/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerMetadataItemDto } from './CustomerMetadataItemDto';
import {
    CustomerMetadataItemDtoFromJSON,
    CustomerMetadataItemDtoFromJSONTyped,
    CustomerMetadataItemDtoToJSON,
} from './CustomerMetadataItemDto';

/**
 * 
 * @export
 * @interface CustomersMetadataListResponseDto
 */
export interface CustomersMetadataListResponseDto {
    /**
     * List of customers metadata
     * @type {Array<CustomerMetadataItemDto>}
     * @memberof CustomersMetadataListResponseDto
     */
    customers: Array<CustomerMetadataItemDto>;
}

/**
 * Check if a given object implements the CustomersMetadataListResponseDto interface.
 */
export function instanceOfCustomersMetadataListResponseDto(value: object): value is CustomersMetadataListResponseDto {
    if (!('customers' in value) || value['customers'] === undefined) return false;
    return true;
}

export function CustomersMetadataListResponseDtoFromJSON(json: any): CustomersMetadataListResponseDto {
    return CustomersMetadataListResponseDtoFromJSONTyped(json, false);
}

export function CustomersMetadataListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomersMetadataListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'customers': ((json['customers'] as Array<any>).map(CustomerMetadataItemDtoFromJSON)),
    };
}

export function CustomersMetadataListResponseDtoToJSON(value?: CustomersMetadataListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customers': ((value['customers'] as Array<any>).map(CustomerMetadataItemDtoToJSON)),
    };
}

