/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerMetadataItemDto
 */
export interface CustomerMetadataItemDto {
    /**
     * Customer metadata ID
     * @type {string}
     * @memberof CustomerMetadataItemDto
     */
    id: string;
    /**
     * Company name
     * @type {string}
     * @memberof CustomerMetadataItemDto
     */
    name: string;
}

/**
 * Check if a given object implements the CustomerMetadataItemDto interface.
 */
export function instanceOfCustomerMetadataItemDto(value: object): value is CustomerMetadataItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CustomerMetadataItemDtoFromJSON(json: any): CustomerMetadataItemDto {
    return CustomerMetadataItemDtoFromJSONTyped(json, false);
}

export function CustomerMetadataItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerMetadataItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CustomerMetadataItemDtoToJSON(value?: CustomerMetadataItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

