/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerResponseDto } from './CustomerResponseDto';
import {
    CustomerResponseDtoFromJSON,
    CustomerResponseDtoFromJSONTyped,
    CustomerResponseDtoToJSON,
} from './CustomerResponseDto';
import type { PaginationDetailsDto } from './PaginationDetailsDto';
import {
    PaginationDetailsDtoFromJSON,
    PaginationDetailsDtoFromJSONTyped,
    PaginationDetailsDtoToJSON,
} from './PaginationDetailsDto';

/**
 * 
 * @export
 * @interface CustomerListResponseDto
 */
export interface CustomerListResponseDto {
    /**
     * 
     * @type {Array<CustomerResponseDto>}
     * @memberof CustomerListResponseDto
     */
    data: Array<CustomerResponseDto>;
    /**
     * 
     * @type {PaginationDetailsDto}
     * @memberof CustomerListResponseDto
     */
    pagination: PaginationDetailsDto;
}

/**
 * Check if a given object implements the CustomerListResponseDto interface.
 */
export function instanceOfCustomerListResponseDto(value: object): value is CustomerListResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function CustomerListResponseDtoFromJSON(json: any): CustomerListResponseDto {
    return CustomerListResponseDtoFromJSONTyped(json, false);
}

export function CustomerListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CustomerResponseDtoFromJSON)),
        'pagination': PaginationDetailsDtoFromJSON(json['pagination']),
    };
}

export function CustomerListResponseDtoToJSON(value?: CustomerListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(CustomerResponseDtoToJSON)),
        'pagination': PaginationDetailsDtoToJSON(value['pagination']),
    };
}

