/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventListItemDto } from './EventListItemDto';
import {
    EventListItemDtoFromJSON,
    EventListItemDtoFromJSONTyped,
    EventListItemDtoToJSON,
} from './EventListItemDto';

/**
 * 
 * @export
 * @interface EventListResponseDto
 */
export interface EventListResponseDto {
    /**
     * List of events
     * @type {Array<EventListItemDto>}
     * @memberof EventListResponseDto
     */
    events: Array<EventListItemDto>;
}

/**
 * Check if a given object implements the EventListResponseDto interface.
 */
export function instanceOfEventListResponseDto(value: object): value is EventListResponseDto {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function EventListResponseDtoFromJSON(json: any): EventListResponseDto {
    return EventListResponseDtoFromJSONTyped(json, false);
}

export function EventListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(EventListItemDtoFromJSON)),
    };
}

export function EventListResponseDtoToJSON(value?: EventListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(EventListItemDtoToJSON)),
    };
}

