/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventMetadataItemDto } from './EventMetadataItemDto';
import {
    EventMetadataItemDtoFromJSON,
    EventMetadataItemDtoFromJSONTyped,
    EventMetadataItemDtoToJSON,
} from './EventMetadataItemDto';

/**
 * 
 * @export
 * @interface EventsMetadataListResponseDto
 */
export interface EventsMetadataListResponseDto {
    /**
     * List of events metadata
     * @type {Array<EventMetadataItemDto>}
     * @memberof EventsMetadataListResponseDto
     */
    events: Array<EventMetadataItemDto>;
}

/**
 * Check if a given object implements the EventsMetadataListResponseDto interface.
 */
export function instanceOfEventsMetadataListResponseDto(value: object): value is EventsMetadataListResponseDto {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function EventsMetadataListResponseDtoFromJSON(json: any): EventsMetadataListResponseDto {
    return EventsMetadataListResponseDtoFromJSONTyped(json, false);
}

export function EventsMetadataListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsMetadataListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(EventMetadataItemDtoFromJSON)),
    };
}

export function EventsMetadataListResponseDtoToJSON(value?: EventsMetadataListResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'events': ((value['events'] as Array<any>).map(EventMetadataItemDtoToJSON)),
    };
}

