/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventMetadataItemDto
 */
export interface EventMetadataItemDto {
    /**
     * Event metadata ID
     * @type {string}
     * @memberof EventMetadataItemDto
     */
    id: string;
    /**
     * Event name
     * @type {string}
     * @memberof EventMetadataItemDto
     */
    name: string;
}

/**
 * Check if a given object implements the EventMetadataItemDto interface.
 */
export function instanceOfEventMetadataItemDto(value: object): value is EventMetadataItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function EventMetadataItemDtoFromJSON(json: any): EventMetadataItemDto {
    return EventMetadataItemDtoFromJSONTyped(json, false);
}

export function EventMetadataItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventMetadataItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function EventMetadataItemDtoToJSON(value?: EventMetadataItemDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

