/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventVenueDto
 */
export interface EventVenueDto {
    /**
     * City where the event is taking place
     * @type {string}
     * @memberof EventVenueDto
     */
    city: string;
    /**
     * Venue name
     * @type {string}
     * @memberof EventVenueDto
     */
    venue: string;
}

/**
 * Check if a given object implements the EventVenueDto interface.
 */
export function instanceOfEventVenueDto(value: object): value is EventVenueDto {
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    return true;
}

export function EventVenueDtoFromJSON(json: any): EventVenueDto {
    return EventVenueDtoFromJSONTyped(json, false);
}

export function EventVenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventVenueDto {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'],
        'venue': json['venue'],
    };
}

export function EventVenueDtoToJSON(value?: EventVenueDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'city': value['city'],
        'venue': value['venue'],
    };
}

