/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthControllerCheckV1200ResponseInfoValue
 */
export interface HealthControllerCheckV1200ResponseInfoValue {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof HealthControllerCheckV1200ResponseInfoValue
     */
    status: string;
}

/**
 * Check if a given object implements the HealthControllerCheckV1200ResponseInfoValue interface.
 */
export function instanceOfHealthControllerCheckV1200ResponseInfoValue(value: object): value is HealthControllerCheckV1200ResponseInfoValue {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthControllerCheckV1200ResponseInfoValueFromJSON(json: any): HealthControllerCheckV1200ResponseInfoValue {
    return HealthControllerCheckV1200ResponseInfoValueFromJSONTyped(json, false);
}

export function HealthControllerCheckV1200ResponseInfoValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthControllerCheckV1200ResponseInfoValue {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': json['status'],
    };
}

export function HealthControllerCheckV1200ResponseInfoValueToJSON(value?: HealthControllerCheckV1200ResponseInfoValue | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'status': value['status'],
    };
}

