/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationDetailsDto
 */
export interface PaginationDetailsDto {
    /**
     * Current page number
     * @type {number}
     * @memberof PaginationDetailsDto
     */
    currentPage: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PaginationDetailsDto
     */
    limit: number;
    /**
     * Total number of pages available
     * @type {number}
     * @memberof PaginationDetailsDto
     */
    totalPages: number;
    /**
     * Total number of customers
     * @type {number}
     * @memberof PaginationDetailsDto
     */
    totalCustomers: number;
}

/**
 * Check if a given object implements the PaginationDetailsDto interface.
 */
export function instanceOfPaginationDetailsDto(value: object): value is PaginationDetailsDto {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalCustomers' in value) || value['totalCustomers'] === undefined) return false;
    return true;
}

export function PaginationDetailsDtoFromJSON(json: any): PaginationDetailsDto {
    return PaginationDetailsDtoFromJSONTyped(json, false);
}

export function PaginationDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['currentPage'],
        'limit': json['limit'],
        'totalPages': json['totalPages'],
        'totalCustomers': json['totalCustomers'],
    };
}

export function PaginationDetailsDtoToJSON(value?: PaginationDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentPage': value['currentPage'],
        'limit': value['limit'],
        'totalPages': value['totalPages'],
        'totalCustomers': value['totalCustomers'],
    };
}

