/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrimarySupportContactDto
 */
export interface PrimarySupportContactDto {
    /**
     * First name of the support contact
     * @type {string}
     * @memberof PrimarySupportContactDto
     */
    firstName: string;
    /**
     * Last name of the support contact
     * @type {string}
     * @memberof PrimarySupportContactDto
     */
    lastName: string;
    /**
     * Support email address
     * @type {string}
     * @memberof PrimarySupportContactDto
     */
    supportEmail: string;
    /**
     * Phone number of the support contact
     * @type {string}
     * @memberof PrimarySupportContactDto
     */
    phoneNumber: string;
    /**
     * Support URL
     * @type {string}
     * @memberof PrimarySupportContactDto
     */
    supportUrl: string;
}

/**
 * Check if a given object implements the PrimarySupportContactDto interface.
 */
export function instanceOfPrimarySupportContactDto(value: object): value is PrimarySupportContactDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('supportEmail' in value) || value['supportEmail'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('supportUrl' in value) || value['supportUrl'] === undefined) return false;
    return true;
}

export function PrimarySupportContactDtoFromJSON(json: any): PrimarySupportContactDto {
    return PrimarySupportContactDtoFromJSONTyped(json, false);
}

export function PrimarySupportContactDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimarySupportContactDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'supportEmail': json['supportEmail'],
        'phoneNumber': json['phoneNumber'],
        'supportUrl': json['supportUrl'],
    };
}

export function PrimarySupportContactDtoToJSON(value?: PrimarySupportContactDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'supportEmail': value['supportEmail'],
        'phoneNumber': value['phoneNumber'],
        'supportUrl': value['supportUrl'],
    };
}

