/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenApiResponseDto
 */
export interface RefreshTokenApiResponseDto {
    /**
     * Access token using refresh token
     * @type {string}
     * @memberof RefreshTokenApiResponseDto
     */
    access_token: string;
}

/**
 * Check if a given object implements the RefreshTokenApiResponseDto interface.
 */
export function instanceOfRefreshTokenApiResponseDto(value: object): value is RefreshTokenApiResponseDto {
    if (!('access_token' in value) || value['access_token'] === undefined) return false;
    return true;
}

export function RefreshTokenApiResponseDtoFromJSON(json: any): RefreshTokenApiResponseDto {
    return RefreshTokenApiResponseDtoFromJSONTyped(json, false);
}

export function RefreshTokenApiResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenApiResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
    };
}

export function RefreshTokenApiResponseDtoToJSON(value?: RefreshTokenApiResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['access_token'],
    };
}

