/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaceResult } from './PlaceResult';
import {
    PlaceResultFromJSON,
    PlaceResultFromJSONTyped,
    PlaceResultToJSON,
} from './PlaceResult';

/**
 * 
 * @export
 * @interface ReverseGeocodeApiResponse
 */
export interface ReverseGeocodeApiResponse {
    /**
     * 
     * @type {PlaceResult}
     * @memberof ReverseGeocodeApiResponse
     */
    data: PlaceResult;
}

/**
 * Check if a given object implements the ReverseGeocodeApiResponse interface.
 */
export function instanceOfReverseGeocodeApiResponse(value: object): value is ReverseGeocodeApiResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ReverseGeocodeApiResponseFromJSON(json: any): ReverseGeocodeApiResponse {
    return ReverseGeocodeApiResponseFromJSONTyped(json, false);
}

export function ReverseGeocodeApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReverseGeocodeApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PlaceResultFromJSON(json['data']),
    };
}

export function ReverseGeocodeApiResponseToJSON(value?: ReverseGeocodeApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': PlaceResultToJSON(value['data']),
    };
}

