/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleStatusDto
 */
export interface ToggleStatusDto {
    /**
     * Whether to enable (true) or disable (false) the customer
     * @type {boolean}
     * @memberof ToggleStatusDto
     */
    enable: boolean;
}

/**
 * Check if a given object implements the ToggleStatusDto interface.
 */
export function instanceOfToggleStatusDto(value: object): value is ToggleStatusDto {
    if (!('enable' in value) || value['enable'] === undefined) return false;
    return true;
}

export function ToggleStatusDtoFromJSON(json: any): ToggleStatusDto {
    return ToggleStatusDtoFromJSONTyped(json, false);
}

export function ToggleStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'enable': json['enable'],
    };
}

export function ToggleStatusDtoToJSON(value?: ToggleStatusDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enable': value['enable'],
    };
}

