/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * User email address
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;
    /**
     * User full name
     * @type {string}
     * @memberof UpdateUserDto
     */
    fullName?: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof UpdateUserDto
     */
    avatarUrl?: string;
    /**
     * User phone number
     * @type {string}
     * @memberof UpdateUserDto
     */
    phone?: string;
    /**
     * User type
     * @type {string}
     * @memberof UpdateUserDto
     */
    userType?: UpdateUserDtoUserTypeEnum;
    /**
     * User status
     * @type {string}
     * @memberof UpdateUserDto
     */
    status?: UpdateUserDtoStatusEnum;
}


/**
 * @export
 */
export const UpdateUserDtoUserTypeEnum = {
    Admin: 'admin',
    User: 'user',
    Customer: 'customer'
} as const;
export type UpdateUserDtoUserTypeEnum = typeof UpdateUserDtoUserTypeEnum[keyof typeof UpdateUserDtoUserTypeEnum];

/**
 * @export
 */
export const UpdateUserDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;
export type UpdateUserDtoStatusEnum = typeof UpdateUserDtoStatusEnum[keyof typeof UpdateUserDtoStatusEnum];


/**
 * Check if a given object implements the UpdateUserDto interface.
 */
export function instanceOfUpdateUserDto(value: object): value is UpdateUserDto {
    return true;
}

export function UpdateUserDtoFromJSON(json: any): UpdateUserDto {
    return UpdateUserDtoFromJSONTyped(json, false);
}

export function UpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'userType': json['userType'] == null ? undefined : json['userType'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateUserDtoToJSON(value?: UpdateUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'fullName': value['fullName'],
        'avatarUrl': value['avatarUrl'],
        'phone': value['phone'],
        'userType': value['userType'],
        'status': value['status'],
    };
}

