/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomerDto
 */
export interface UpdateCustomerDto {
    /**
     * XCD Customer user ID
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    userId?: string;
    /**
     * Customer name
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    customerName?: string;
    /**
     * Contact email address
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    contactEmail?: string;
    /**
     * Contact phone number
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    contactPhone?: string;
    /**
     * Company ID
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    companyId?: string;
    /**
     * Company name
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    companyName?: string;
    /**
     * Customer location
     * @type {object}
     * @memberof UpdateCustomerDto
     */
    location?: object;
    /**
     * Customer status
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    status?: UpdateCustomerDtoStatusEnum;
    /**
     * Total events count
     * @type {number}
     * @memberof UpdateCustomerDto
     */
    totalEvents?: number;
}


/**
 * @export
 */
export const UpdateCustomerDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;
export type UpdateCustomerDtoStatusEnum = typeof UpdateCustomerDtoStatusEnum[keyof typeof UpdateCustomerDtoStatusEnum];


/**
 * Check if a given object implements the UpdateCustomerDto interface.
 */
export function instanceOfUpdateCustomerDto(value: object): value is UpdateCustomerDto {
    return true;
}

export function UpdateCustomerDtoFromJSON(json: any): UpdateCustomerDto {
    return UpdateCustomerDtoFromJSONTyped(json, false);
}

export function UpdateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'contactEmail': json['contactEmail'] == null ? undefined : json['contactEmail'],
        'contactPhone': json['contactPhone'] == null ? undefined : json['contactPhone'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'companyName': json['companyName'] == null ? undefined : json['companyName'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalEvents': json['totalEvents'] == null ? undefined : json['totalEvents'],
    };
}

export function UpdateCustomerDtoToJSON(value?: UpdateCustomerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'customerName': value['customerName'],
        'contactEmail': value['contactEmail'],
        'contactPhone': value['contactPhone'],
        'companyId': value['companyId'],
        'companyName': value['companyName'],
        'location': value['location'],
        'status': value['status'],
        'totalEvents': value['totalEvents'],
    };
}

