/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomerDto
 */
export interface UpdateCustomerDto {
    /**
     * Customer name
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    customerName?: string;
    /**
     * Contact email address
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    contactEmail?: string;
    /**
     * Contact phone number
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    contactPhone?: string;
    /**
     * Customer location
     * @type {object}
     * @memberof UpdateCustomerDto
     */
    location?: object;
    /**
     * Phone country code (e.g., +1, +44, +91)
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    countryCode?: string;
}

/**
 * Check if a given object implements the UpdateCustomerDto interface.
 */
export function instanceOfUpdateCustomerDto(value: object): value is UpdateCustomerDto {
    return true;
}

export function UpdateCustomerDtoFromJSON(json: any): UpdateCustomerDto {
    return UpdateCustomerDtoFromJSONTyped(json, false);
}

export function UpdateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'contactEmail': json['contactEmail'] == null ? undefined : json['contactEmail'],
        'contactPhone': json['contactPhone'] == null ? undefined : json['contactPhone'],
        'location': json['location'] == null ? undefined : json['location'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
    };
}

export function UpdateCustomerDtoToJSON(value?: UpdateCustomerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customerName': value['customerName'],
        'contactEmail': value['contactEmail'],
        'contactPhone': value['contactPhone'],
        'location': value['location'],
        'countryCode': value['countryCode'],
    };
}

