/* tslint:disable */
/* eslint-disable */
/**
 * XCD APIs
 * API documentation for the backend services of XCD
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * User ID
     * @type {string}
     * @memberof UserResponseDto
     */
    id: string;
    /**
     * User email address
     * @type {string}
     * @memberof UserResponseDto
     */
    email: string;
    /**
     * User full name
     * @type {string}
     * @memberof UserResponseDto
     */
    fullName: string;
    /**
     * User avatar URL
     * @type {string}
     * @memberof UserResponseDto
     */
    avatarUrl?: string;
    /**
     * User phone number
     * @type {string}
     * @memberof UserResponseDto
     */
    phone?: string;
    /**
     * User type
     * @type {string}
     * @memberof UserResponseDto
     */
    userType: string;
    /**
     * User status
     * @type {string}
     * @memberof UserResponseDto
     */
    status: string;
}

/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): value is UserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('userType' in value) || value['userType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'fullName': json['fullName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'userType': json['userType'],
        'status': json['status'],
    };
}

export function UserResponseDtoToJSON(value?: UserResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'fullName': value['fullName'],
        'avatarUrl': value['avatarUrl'],
        'phone': value['phone'],
        'userType': value['userType'],
        'status': value['status'],
    };
}

